### PR TITLE
Add eval-only arguments and W&B resume options

### PR DESCRIPTION
**Pull request by eric11eca**
- [x] Add `eval_only` option to arguments
- [x] Evaluation mode in the training code
- [x] Allow a more flexible resume option for W&B
- [x] Allow writing W&B logs to defined local_dir

### CODE REVIEW

**Comment by kylematoba** [comment]
Just so we have a natural language record: it seems like 

`eval_only` is a synonym for `do_train = False; do_valid = False; do_test = True`.

**Comment by AleHD** [comment]
Do we need to merge  `meditron_run` scripts?

**Comment by eric11eca** [comment]
> Do we need to merge `meditron_run` scripts?

Nope, somehow they were in the commit as well...

**Comment by AleHD** [comment]
Closing in favor of #87.

**Pull request closed without merging**
