### PR TITLE
Update weights2megatron.py

### PR DESCRIPTION
**Pull request by dumpmemory**
fix key typo

### CODE REVIEW

**Review by martinjaggi — APPROVED** [review]
@AleHD do you agree?

**Comment by AleHD** [comment]
It looks like neither 30 nor 32 is correct. The [meta research paper](https://ai.meta.com/research/publications/llama-2-open-foundation-and-fine-tuned-chat-models/) mentions the models 7B, 13B, 34B, 70B. But interestingly, neither the [huggingface repo](https://ai.meta.com/research/publications/llama-2-open-foundation-and-fine-tuned-chat-models/) nor the weights provided by meta offer the 34B option...

**Comment by martinjaggi** [comment]
the llama authors said on github at some point that it was their typo?

**Comment by AleHD** [comment]
Right, I was only thinking about llama2 but llama-1-30B is indeed a thing. I'll merge this request now :)

**Pull request merged**
