### PR TITLE
Add CodeLlama support

### PR DESCRIPTION
**Pull request by andreaskoepf**
Main differences of codellama:
- sequence_length: 16384
- rope_theta: 1e6
- vocabulary size: 32016

Note: Once support for rope_theta has been added to hf transformers (see https://github.com/huggingface/transformers/pull/25740) the args.rope_theta value should also be applied in megatron2hf.py.

### CODE REVIEW

**Comment by panx27** [comment]
The vocab size of the 34b model is still 32000

**Comment by panx27** [comment]
I think the mapping also needs to be updated: https://github.com/epfLLM/Megatron-LLM/compare/main...panx27:Megatron-LLM:codellama_test#diff-ec4ffbea89a2008356ff84590b89264ef61b775a46422546296f030923e6c3bbL16-L20

**Comment by andreaskoepf** [comment]
The tokenizer situation is indeed a bit special and unfortunately not only dependent on size, a check might be >13b or "Python" in the name:

```
find -iname tokenizer.model -exec md5sum '{}' \;
9e597e72392fd4005529a33f2bf708ba  ./CodeLlama-7b/tokenizer.model
9e597e72392fd4005529a33f2bf708ba  ./CodeLlama-13b/tokenizer.model
9e597e72392fd4005529a33f2bf708ba  ./CodeLlama-7b-Instruct/tokenizer.model
9e597e72392fd4005529a33f2bf708ba  ./CodeLlama-13b-Instruct/tokenizer.model
eeec4125e9c7560836b4873b6f8e3025  ./CodeLlama-7b-Python/tokenizer.model
eeec4125e9c7560836b4873b6f8e3025  ./CodeLlama-13b-Python/tokenizer.model
eeec4125e9c7560836b4873b6f8e3025  ./CodeLlama-34b-Python/tokenizer.model
eeec4125e9c7560836b4873b6f8e3025  ./CodeLlama-34b/tokenizer.model
eeec4125e9c7560836b4873b6f8e3025  ./CodeLlama-34b-Instruct/tokenizer.model
```

**Comment by andreaskoepf** [comment]
@panx27 I have tested so far only finet-tuning the 13b version codellama vanilla version .. if you happen to try 34b please let me know if it works with the current version of the code.

**Comment by panx27** [comment]
@andreaskoepf  I have tested the conversion process (meta -> megatron, sharding, megatron -> hf) and the training process for the 34b model on the current version of your code. The results look good to me. 

There's a small modification needed. In [here](https://github.com/andreaskoepf/epfl-megatron/blob/codellama_support/weights2megatron/weights2megatron.py#L187), the default value should be set to 32,000. As it stands, the current logic will assign a vocab size of 32,016 to the 34b model, which is not what we want.

**Comment by andreaskoepf** [comment]
Thanks a lot for testing!

> There's a small modification needed.

Oh yes, I forgot to remove that line.. will correct now.

**Review by martinjaggi — APPROVED** [review]

**Pull request merged**
